int absolute(int);
double mySqrt(double);
double reciprocalFunction(double);
int factorial(unsigned int);
double myPow(double, int);
double myPow(double, double);
double mySin(double);
double myCos(double);
double myTan(double);
double mySec(double);
double myCsc(double);
double myCot(double);
double myAsin(double);
double myAcos(double);
double myAtan(double);
double myAsec(double);
double myAcsc(double);
double myAcot(double);
double mySh(double);
double myCh(double);
double myTh(double);
double mySech(double);
double myCsch(double);
double myCoth(double);
double myAsh(double);
double myAch(double);
double myAth(double);
int myFloor(double);
int myCeil(double);
double myPi();
double myE();
double mySquare(double);
double myMod(double, double);
double myTenDeg(double);
double myExp(double, double);
double myLg(double);
double myLn(double);
double myCube(double);
double myCbrt(double);
double myRoot(double, double);
double myTwoDeg(double);
double myLog(double, double);
double myEx(double);